# Generated by Django 3.2.9 on 2021-11-12 07:28

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shapes',
            name='classmane',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='classname'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shapes',
            name='geom',
            field=django.contrib.gis.db.models.fields.PolygonField(default=0, srid=4326),
            preserve_default=False,
        ),
    ]
